#!/usr/bin/env sh

# workaround for automatically loading scripts on startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5


# yabai rules
yabai -m rule --add title='Preferences$' manage=off layer=above
yabai -m rule --add title='Calculator' manage=off layer=above
yabai -m rule --add title='TinkerTool' manage=off layer=above
yabai -m rule --add title='Opening$' manage=off layer=above
yabai -m rule --add app='System Preferences' manage=off layer=above
yabai -m rule --add app='App Store' manage=off layer=above
yabai -m rule --add app='Finder' manage=off layer=above
yabai -m rule --add app='Installer' manage=off layer=above
yabai -m rule --add app='Enpass' manage=off layer=above
yabai -m rule --add app='Simulator' manage=off layer=above


yabai -m rule --add app='Code' space=1
# yabai -m rule --add app='Alacritty' space=2
yabai -m rule --add app='Chrome' space=3
yabai -m rule --add app='Brave' space=4
yabai -m rule --add app='Slack' space=5
yabai -m rule --add app='WhatsApp' space=6
yabai -m rule --add app='Signal' space=6


# yabai signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null ||yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null ||yabai -m window --focus mouse"

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

echo "yabai configuration loaded.."

